### ISSUE TITLE
Dynamic Readme listing all available pkgs

### ISSUE THREAD

**Issue by Azathothas** [leleliu008/ppkg-formula-repository-official-core#2]
Hi, would you be interested in something like https://github.com/Azathothas/ndk-pkg-formula-repository-fork-core?
I can fork and send a PR, if not, then I will have to maintain yet another fork.

Browsing through each yaml file is tedious, and json/yaml files would help me automate certain things for https://github.com/Azathothas/Toolpacks, like I have done for android (I depend on your ndk-pkg for 90% of the android binaries)

**Comment by leleliu008** [comment]
PRs are welcomed.

**Comment by leleliu008** [comment]
```
ppkg ls-available -v --yaml
```

```
ppkg ls-available -v --json
```

`pkg` and `ndk-pkg` have the same user interface.

**Comment by Azathothas** [comment]
It might pollute the main page with only linux packages.
Should the README.md be generated inside ./formula/linux/ instead?
Since ppkg formula also contain formulas for *bsd & macos

**Comment by Azathothas** [comment]
> feel free to request packages and features, I will do my effort to add or implemtent them.

I keep asking if you have a social account (telegram, discord, etc) but alas seems GitHub is the only one you use.
It will look like spam if I constantly request packages.

**Comment by leleliu008** [comment]
ppkg is-available only list packages match your current os. That's to say, only Linux packages will be listed on Linux system.

**Comment by leleliu008** [comment]
I do not use any social media. Come here to connect me.

**Comment by Azathothas** [comment]
> ppkg ls-available only list packages match your current os. That's to say, only Linux packages will be listed on Linux system.

I meant for the dynamically generated readme, where should I place it?
On the main page or in one of the sub dirs



> I do not use any social media. Come here to connect me.

Understandable. Thank you for everything. 
I ran into another issue at: https://github.com/Azathothas/Toolpacks/issues/30 
The upstream released binaries are AppImage and not true static binary and only contains x86_64
https://github.com/bpftrace/bpftrace/releases/download/v0.21.2/bpftrace
![image](https://github.com/user-attachments/assets/395ac234-993a-4a6e-bc87-42877fb52c11)

I tried compiling, it compiles but doesn't work

**Comment by leleliu008** [comment]
> I meant for the dynamically generated readme, where should I place it?
> On the main page or in one of the sub dirs

I'm sorry, I din't quite catch you. You want to generate a README and commit to this repo?

**Comment by Azathothas** [comment]
> > I meant for the dynamically generated readme, where should I place it?
> > On the main page or in one of the sub dirs
> 
> I'm sorry, I din't quite catch you. You want to generate a README and commit to this repo?

Yes a dynamically generated one which will list all pkgs in table like format like in this repo:
https://github.com/Azathothas/ndk-pkg-formula-repository-fork-core

**Comment by leleliu008** [comment]
I do not think it is needed. To me, I do not want to see such long list

**Comment by Azathothas** [comment]
I see. 
I will maintain a fork then.
Thanks!

**Comment by Azathothas** [comment]
Hi, this is sort of related, so I didn't want to create an issue.
I wanted a way to fetch the `version` of packages without installing `ppkg` & without manually crafting grep/sed cmd

In the past, I have done it at: https://github.com/Azathothas/ndk-pkg-formula-repository-fork-core/blob/main/pkgs.json
With something like: https://github.com/Azathothas/ndk-pkg-formula-repository-fork-core/blob/main/.github/workflows/list_ndk_pkgs.yaml#L80

But that is still a big json. 
Would you be interested in providing an easier way to fetch `version`
We need it to detect if building is necessary or not

Currently, I am fetching version in this way:
- https://github.com/pkgforge/soarpkgs/blob/main/binaries/wget/static.ppkg.stable.yaml#L50

**Comment by leleliu008** [comment]
> I wanted a way to fetch the `version` of packages without installing `ppkg` & without manually crafting grep/sed cmd

what's the problem of this way?

you want a standalone tool to fetch a formula's version?

**Comment by Azathothas** [comment]
> what's the problem of this way?

each pkg needs it's own sed/grep filter to parse it correctly
same sed/grep expression doesn't work

> you want a standalone tool to fetch a formula's version?
Rather, I want a program friendly format like json/yaml that has the `version` field, 
currently, most formula don't have a `version` field

**Comment by leleliu008** [comment]
I could write it in C, but need some time. I have many works to do in hand.

**Comment by Azathothas** [comment]
> I could write it in C, but need some time. I have many works to do in hand.

Sure no worries.
In the meantime, I will generate a json like the `ndk-repo`
