### ISSUE TITLE
Imagemagick's Static Build is Misconfigured

### ISSUE THREAD

**Issue by Azathothas** [leleliu008/ppkg-formula-repository-official-core#5]
Hi, I tested:  https://github.com/Azathothas/ppkg-package-manually-build/actions/runs/10849476750/job/30108758126
![image](https://github.com/user-attachments/assets/07d5ff04-5cc5-43ec-9083-f42d6242a75b)

The final uploaded artefact is : https://github.com/Azathothas/ppkg-package-manually-build/actions/runs/10849476750/artifacts/1930035433
Unzipped:
```bash
🌀 ❯ tree ../imagemagick---linux-x86_64.tar.xz/imagemagick-7.1.1.29-linux-musl-x86_64.tar/imagemagick-7.1.1.29-linux-musl-x86_64  -L 1
../imagemagick---linux-x86_64.tar.xz/imagemagick-7.1.1.29-linux-musl-x86_64.tar/imagemagick-7.1.1.29-linux-musl-x86_64
├── bin
├── etc
├── include
├── lib
└── share
```

It bundled everything...
![image](https://github.com/user-attachments/assets/cd63b6af-67ea-4f64-bced-8d7867e2323e)

But the final binary is indeed static:
```bash
magick:            ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, BuildID[sha1]=99befb56de8ca5e7e32d842cbe6a2c98086565f0, stripped
```

I think i should avoid including other things or there should be a flag to build or include progs only

**Comment by Azathothas** [comment]
I found https://github.com/ruanformigoni/imagemagick-static-musl
The build only take 1-2 min to finish

**Comment by leleliu008** [comment]
> I found https://github.com/ruanformigoni/imagemagick-static-musl The build only take 1-2 min to finish

`ppkg` build all dependencies from source, but https://github.com/ruanformigoni/imagemagick-static-musl only build imagemagick itself from source, their dependencies are install via apk.

**Comment by leleliu008** [comment]
> I think i should avoid including other things or there should be a flag to build or include progs only

you can repack it after downloading. or remove other files and leave what you want.

`ppkg pack` command has `--exclude <ITEM>`, but I do not provide it for github actions.

**Comment by Azathothas** [comment]
I see.
Thank you for answering.

**Comment by leleliu008** [comment]
@Azathothas I wonder if the fully statically linked imagemagick executable really work.

**Comment by Azathothas** [comment]
Extracted from https://github.com/Azathothas/ppkg-package-manually-build/actions/runs/10849476750/artifacts/1930035433
DL: https://pub.ajam.dev/temp/magick
The --help works:
```bash
Usage: magick tool [ {option} | {image} ... ] {output_image}
Usage: magick [ {option} | {image} ... ] {output_image}
       magick [ {option} | {image} ... ] -script {filename} [ {script_args} ...]
       magick -help | -version | -usage | -list {option}

```

After symlinked to `conver`
```bash
🌀 ❯ ln -s magick convert
🌀 ❯ ./convert
Version: ImageMagick 7.1.1-29 Q16-HDRI x86_64 21991 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP(4.5)
Delegates (built-in): bzlib freetype heic jng jp2 jpeg jxl lcms lqr ltdl lzma openexr png tiff webp zlib zstd
Compiler: gcc (13.2)
Usage: convert [options ...] file [ [options ...] file ...] [options ...] file

Image Settings:
  -adjoin              join images into a single multi-image file
  -affine matrix       affine transform matrix
  -alpha option        activate, deactivate, reset, or set the alpha channel
  -antialias           remove pixel-aliasing
 ---REMOVED--- 
```

Testing feature
```
wget -q https://portable-linux-apps.github.io/icons/steam.png
🌀 ❯ ./convert steam.png -resize "128x128" steam_128.png
convert: UnableToOpenConfigureFile `delegates.xml' @ warning/configure.c/GetConfigureOptions/722.
convert: NoDecodeDelegateForThisImageFormat `PNG' @ error/constitute.c/ReadImage/746.
convert: NoImagesDefined `steam_128.png' @ error/convert.c/ConvertImageCommand/3362.
```

Using https://github.com/ruanformigoni/imagemagick-static-musl/releases/download/c1c5775/magick-x86_64 works
```bash
🌀 ❯ ./magick-x86_64 convert steam.png -resize "128x128" steam_128.png
```
![image](https://github.com/user-attachments/assets/c77dbe4e-377e-4579-9383-a8d94bfe006d)

**Comment by leleliu008** [comment]
> Using https://github.com/ruanformigoni/imagemagick-static-musl/releases/download/c1c5775/magick-x86_64 works

It is not fully linked. It is mostly statically linked.
