### ISSUE TITLE
Request: Appstream Cli

### ISSUE THREAD

**Issue by Azathothas** [leleliu008/ppkg-formula-repository-official-core#7]
Hi, hope you are doing well.
I have been busy over at https://github.com/Azathothas/Toolpacks-Extras, so very far away from static things..

Recently, I found the need to use appstream-cli: https://github.com/ximion/appstream
I tried building it, but found out it's not possible.
I came across https://github.com/ximion/appstream/issues/128
That lead me to this: https://github.com/probonopd/static-tools/pull/47
https://github.com/probonopd/go-appimage/issues/272#issuecomment-2453384090

Would appreciate it if you could give it a look and say if it is indeed impossible to get a static appstream-cli
Thanks!

**Comment by leleliu008** [comment]
I will look into this tonight.

**Comment by leleliu008** [comment]
appstream package has been added in this repo https://github.com/leleliu008/ppkg-formula-repository-official-core/blob/master/formula/appstream.yml

It could be built as a fully statically linked executable against `glibc`. 

If you want to built it as a fully statically linked executable against `musl-libc`, please remove `systemd` depencency, beacuase `systemd` needs a lot of patches for `musl-libc`, I have not done for it.

```bash
summary: Tools and libraries to work with AppStream metadata
web-url: https://www.freedesktop.org/wiki/Distributions/AppStream/
src-url: https://github.com/ximion/appstream/archive/refs/tags/v1.0.3.tar.gz
src-sha: dd7222519b5d855124fa803ce82a7cbf090ac6b2e44a5bc515e729b1f20a63ae
license: LGPL-2.1-or-later
dep-pkg: libxmlb libxml2 libyaml libcurl
dep-upp: gettext-tools itstool xsltproc docbook-xsl gperf

dopatch: gsed -i '/tests/d' meson.build

install: |
    mesonw \
        -Dsystemd=false \
        -Dstemming=false \
        -Dvapi=true \
        -Dgir=false \
        -Ddocs=false \
        -Dapidocs=false \
        -Dinstall-docs=false
```

I have no idea if it really works, I had never used it, you could test it.

**Comment by leleliu008** [comment]
https://github.com/fpliu1214/ppkg-package-manually-build/actions/runs/11711973185

**Comment by Samueru-sama** [comment]
> https://github.com/fpliu1214/ppkg-package-manually-build/actions/runs/11711973185

Hey just in case, the binary isn't fully static: 

![image](https://github.com/user-attachments/assets/ba4c83c1-ffb0-4e09-b37d-f6cdb88ca05d)

**Comment by leleliu008** [comment]
mostly statically linked against `glibc`: https://github.com/fpliu1214/ppkg-package-manually-build/actions/runs/11711973185

fully statically linked against `musl-libc`, without `libsystemd` support: https://github.com/fpliu1214/test/actions/runs/11730041641 

fully statically linked against `glibc` might not work, I didn't build it. if you want to try, please built it by yourself via [[https://github.com/fpliu1214/ppkg-package-manually-build/](https://github.com/fpliu1214/ppkg-package-manually-build/actions/runs/11711973185)](https://github.com/fpliu1214/ppkg-package-manually-build/).

**Comment by Samueru-sama** [comment]
> mostly statically linked against `glibc`: https://github.com/fpliu1214/ppkg-package-manually-build/actions/runs/11711973185
> 
> fully statically linked against `musl-libc`, without `libsystemd` support: https://github.com/fpliu1214/test/actions/runs/11730041641
> 
> fully statically linked against `glibc` might not work, I didn't build it. if you want to try, please built it by yourself via https://github.com/fpliu1214/ppkg-package-manually-build

Thank you!

**Comment by leleliu008** [comment]
I build only x86_64 for you, if you want other arch, please refer to https://github.com/fpliu1214/test/blob/6b6198da4b3a0e74bf794e061208b1ce78eb9537/.github/workflows/appstream.yml

**Comment by Azathothas** [comment]
Thank you so much @leleliu008 

I have commented here https://github.com/probonopd/static-tools/pull/47#issuecomment-2466258436, hopefully they can confirm if it works.

You may close this issue now.
